### ISSUE TITLE
Pouvoir se connecter avec son e-mail

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#102]
# UX Test
## Demande

Après avoir créé un compte (https://github.com/fablab-chaux-de-fonds/Interlab/issues/21), l'utilisateur peut s'authentifier.

En tant qu'utilisateur (lambda), je souhaite pouvoir m'authentifier **avec mon mail** pour accéder a mon profile, réservation, ...

## Résultat attendu
* Cliquer sur "Connexion" si l'utilisateur est sur la page d'accueil ou "Se connecter" si déjà sur la page /accounts/activate/complete/
* S'authentifier (tester les message d'erreur si pas activé ou authentification incorrecte) avec son nom d'utilisateur
* Afficher la page de profile /accounts/profile/

**Comment by melaniethms** [comment]
J'ai pas compris le test. Si c'est se connecter en tant qu'utilisateur lambda est-ce que tu veux que je crée un compte d'abord ? j'ai testé avec mon mail et mdp habituel et ça marche pas mais l'inverse m'aurais surpris. du coup avec le nom du super user et le mdp que tu m'as envoyé sur slack ça marche mais du coup je vois qu'un compte super user. Je vais regarder la suite, mais si tu veux externaliser les tests, des démos scénarios seraient pas mal avec le détail de ce qu'il faut faire exactement et le résultat attendu.

**Comment by ioknox** [comment]
Cette story est en plus de #20 pour permettre de s'authentifier en utilisant sont mail au lieu de son nom d'utilisateur.

**Comment by raphaelmonnard** [comment]
> des démos scénarios seraient pas mal avec le détail de ce qu'il faut faire exactement et le résultat attendu.

Voir https://github.com/fablab-chaux-de-fonds/Interlab/issues/102#issue-1165726220

**Comment by melaniethms** [comment]
toujours ok et la story est vraiment décrite efficacement :)
