### ISSUE TITLE
Validation of user's fields

### ISSUE THREAD

**Issue by ioknox** [fablab-chaux-de-fonds/Interlab#115]
User's forname, lastname (maybe others) should not have specials characters like ":", "/", "<", ">", "{" etc

**Comment by raphaelmonnard** [comment]
The regular expression pattern [^a-zA-Z0-9]+ matches one or more characters that are not alphanumeric (i.e., not letters or digits).

Here's a breakdown of the pattern:

    ^: The caret symbol at the beginning of the pattern means "not". So, [^a-zA-Z0-9] matches any character that is not an uppercase or lowercase letter or a digit.
    +: The plus symbol means "one or more", so [^a-zA-Z0-9]+ matches one or more consecutive non-alphanumeric characters.

For example, the pattern would match strings like !@#$%, ()_+, ^&*(), but would not match strings like hello, 1234, or aBcDeFgH.
