### ISSUE TITLE
problème CSS : réserver machine si pas encore de formation cadre jaune autour du message d'erreur

### ISSUE THREAD

**Issue by suzanneweber** [fablab-chaux-de-fonds/Interlab#170]
<img width="1349" alt="Capture d’écran 2022-12-03 à 15 43 07" src="https://user-images.githubusercontent.com/85431022/205446564-47964904-f1bf-4228-881f-e73ef79df302.png">

**Comment by raphaelmonnard** [comment]
@suzanneweber donner les HEX pour le fond et le text
