### ISSUE TITLE
Problème d'inscription à la newsletter : on ne sait pas si on est inscrit ou pas ?

### ISSUE THREAD

**Issue by suzanneweber** [fablab-chaux-de-fonds/Interlab#171]
#23

**Comment by ioknox** [comment]
"Not a bug, it's a feature" ;D

On enregistre volontairement pas l'information; la gestion de l'inscription est faite complétement hors site.
Les personnes peuvent se désinscrire directement depuis la newsletter.

A réouvrir si vraiment c'est un problème au quel cas il faudra complétement repenser cette partie.

**Comment by raphaelmonnard** [comment]
On n'a pas de petit " feedback check" lorsqu'on tente de s'inscrire depuis une page qui a déjà un autre formulaire

**Comment by ioknox** [comment]
Le problème n'est présent que sur les "sous-pages" : 
![image](https://user-images.githubusercontent.com/12428258/211217617-cc0b5049-3e56-4f86-a57b-39ad9a981408.png)
