### ISSUE TITLE
Pouvoir s'authentifier

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#20]
# UX Test
## Demande
Après avoir créé un compte (#21), l'utilisateur peut s'authentifier.

En tant qu'utilisateur, je souhaite pouvoir m'authentifier pour accéder a mon profile, réservation, ...

## Résultat attendu
* Cliquer sur "Connexion" si l'utilisateur est sur la page d'accueil ou "Se connecter" si déjà sur la page /accounts/activate/complete/
* S'authentifier (tester les message d'erreur si pas activé ou authentification incorrecte) avec son nom d'utilisateur
* Afficher la page de profile /accounts/profile/

**Comment by melaniethms** [comment]
pas la même story que la 102 ? en tout cas comme dans la 102 ça marche

**Comment by melaniethms** [comment]
toujours ok
