### ISSUE TITLE
Pouvoir créer un compte utilisateur

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#21]

**Comment by raphaelmonnard** [comment]
UX test

## Demande:
Afficher la page d'accueil et demander à l'utilisateur de se créer un compte

## Résultat attendu:
* la personne crée un nouveau compte
* la personne comprend les champs qu'elle rempli

**Comment by melaniethms** [comment]
les sous champs prennent méga de la place c'est très indigeste. Pourquoi un champ nom d'utilisateur ? je me souviens même plus quand c'est la dernière fois que j'ai du rentrer ça pour me créer un compte sur un site. De nos jours la pratique courante c'est tu rentres tous les autres champs et le nom d'utilisateur tu peux à la rigueur le renseigner dans ton profil plus tard. et du coup en login on demande l'email voir des fois e-mail ou nom d'utilisateur. La finalité du test c'est la page "Votre compte a été créé avec succès" ? si oui ça marche

**Comment by raphaelmonnard** [comment]
>les sous champs prennent méga de la place c'est très indigeste

Fixed by removing help text: [2d04193](https://github.com/fablab-chaux-de-fonds/Interlab/pull/107/commits/2d041932cdc441d10dc1bd3158802915be667b5a)

>Pourquoi un champ nom d'utilisateur ?

To be discussed with @ioknox
