### ISSUE TITLE
Pouvoir modifier son compte utilisateur

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#22]
# UX Test

## Demande
Après s'être authetifié (https://github.com/fablab-chaux-de-fonds/Interlab/issues/20), l'utilisateur peut modifier son profile.

En tant qu'utilisateur (lambda), je souhaite:

1. Modifer mon profile (e-mail, nom d'utilisateur, nom, prénom)
2. Modifier mon mot de passe
3. Supprimer mon compte

### Modifer mon profile
* Depuis la page /accounts/profile/, l'utilisateur clique sur "Mon profile"
* L'utilisateur change un champs
* L'utilisateur valide la modification - bouton "Mettre à jour"
* L'utilisateur comprends que le champs a été modifié (message en vert en haut de la page de redirection)

### Modifier mon mot de passe
* Depuis la page /accounts/profile/, l'utilisateur clique sur "Mon profile"
* L'utilisateur clique sur "Changer mon mot de passe"
* L'utilisateur rempli le formulaire /accounts/password_change/
* L'utilisateur comprends que le mots de passe a bien été changé (/accounts/password_change/done/)
* L'utilisateur peut cliquer sur "mon compte" pour continuer à naviguer sur la site.

### Supprimer mon compte
* Depuis la page /accounts/profile/, l'utilisateur clique sur "Mon profile"
* L'utilisateur clique sur "Supprimer mon compte"
* L'utilisateur confirme la suppression du compte (/accounts/profile/edit/), ou peut revenir en arrièrre.
* S'il confirme la suppression, l'utilisateur est rediriger à la page d'acceuil avec un message qui confirme la suppression du compte.

**Comment by melaniethms** [comment]
c'est quoi que je dois modifier ? est-ce que j'ose le faire avec le compte superuserFL_test?

**Comment by raphaelmonnard** [comment]
> c'est quoi que je dois modifier ? est-ce que j'ose le faire avec le compte superuserFL_test?

See https://github.com/fablab-chaux-de-fonds/Interlab/issues/22#issue-892497372

**Comment by raphaelmonnard** [comment]
>Inconsistance en fonction des menu "profil"
FIX 71d28eaa374f3c9bd650d58c7a2623a801b3520a and 5a8969310c6c666f32533e5a551f73027dffc19a
