### ISSUE TITLE
Inscription au newsletters

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#23]
# UX Test
## Demande
1. En tant que **visiteur** (et non utilisateur inscrit), je souhaite pouvoir me tenir au courant des nouvelles du FabLab.
2. En tant que **nouvel utilisateur**, je souhaite m'inscrire à la newsletter

### Visiteur
* Sur la page d'accueil, le visiteur rempli sont email en bas de page.
* Le visiteur reçois un message "merci" au dessous du champs e-mail qu'il vient de remplire.

### Nouvel utilisateur
* L'utilisateur se rends sur la page d'inscription (/accounts/register/)
* L'utilisateur coche la case " Je m'abonne à la newsletter"

## Contrôle du test
Pour contrôler que l'utilisateur s'est bien enregistrer, il faudrait se rendre sur newsletter.informaniak.com et vérifier la liste "test"

**Comment by raphaelmonnard** [comment]
> je ne sais pas quel est le but

See: https://github.com/fablab-chaux-de-fonds/Interlab/issues/23#issue-892497501

**Comment by melaniethms** [comment]
je rentre l'e-mail je clique sur le bouton qui change de couleur et c'est tout, pas de message

**Comment by melaniethms** [comment]
en tant qu'utilisateur dois-je avoir un message ? dois-je tester si je suis dans la base de donner ?

**Comment by melaniethms** [comment]
moi j'ai pas de message

**Comment by melaniethms** [comment]
![image](https://user-images.githubusercontent.com/16255861/161986333-f5b09b88-1c37-4a90-bf57-1b757c51a0b5.png)

**Comment by raphaelmonnard** [comment]
Issue with CSRF tocken
