### ISSUE TITLE
Réinitialiser son mot de passe

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#24]
# UX Test
## Demande
En tant qu'utilisateur pas authetifié (déconnecté), je souhaite reinitialiser mon mot de passe car je l'ai perdu.

## Résultat attendu
* L'utilisateur clique sur "connexion"
* L'utilisateur clique sur "Mot de passe oublié"
* L'utilisateur entre sont e-mail
* L'utilisateur comprends qu'il doit regarder ses e-mail
* L'utilisateur clique sur le lien dans le mail
* L'utilisateur fournis un nouveau mot de passe
* L'utilisateur comprends que le mots de passe s'est bien modifié
* L'utilisateur se connecte avec son nouveau mot de passe
* L'utilisateur est connecté sur sa page profile (/accounts/profile/)

**Comment by raphaelmonnard** [comment]
> c'est pas la même story que la 77 ? en tout cas même problème que là bas

Oui, merci pour la remarque, j'ai close #77 

> on est dans quelle page pour la réinitialisation ? je réinitialise le mdp du user "superuserFL_test" ?

See https://github.com/fablab-chaux-de-fonds/Interlab/issues/24#issue-892497623

**Comment by melaniethms** [comment]
je sais pas si on est déjà au niveau du travail du wording mais réinitialisé m'a induit en erreur, j'ai cru que c'est tout mon compte qu'on allait réinitialisée : "Réinitialiser mon mot de pass" ou "m'envoyer un lien par e-mail" ce serait mieux

**Comment by melaniethms** [comment]
si non ça marche

**Comment by raphaelmonnard** [comment]
> je sais pas si on est déjà au niveau du travail du wording mais réinitialisé m'a induit en erreur, j'ai cru que c'est tout mon compte qu'on allait réinitialisée : "Réinitialiser mon mot de pass" ou "m'envoyer un lien par e-mail" ce serait mieux

FIX: [7139064](https://github.com/fablab-chaux-de-fonds/Interlab/pull/107/commits/7139064bbb1d7ecd962dc02a94ab8bbaa64e0423)
