### ISSUE TITLE
Annuler une inscription à un créneau (formation/machine/évènement)

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#28]

**Comment by suzanneweber** [comment]
# UX-Test

## Demande
Vous ne pourrez finalement pas assister à la formation laser pour laquelle vous vous êtes inscrit·e, vous souhaitez donc l'annuler.

/!\ 2 types de réponses si +de 24h avant la formation ou -de 24h avant la formation

**Comment by raphaelmonnard** [comment]
OK pour Laurence
Ajouter une bouton "mes réservation" "sous réserver" puis lien vers me connecter (commentaire 11)
