### ISSUE TITLE
ajouter lien sur "pendant ouverture fablab"-> calendrier

### ISSUE THREAD

**Issue by suzanneweber** [fablab-chaux-de-fonds/Interlab#385]
dans Fabriquez : https://hidora.fablab-chaux-de-fonds.ch/comment-ca-marche/?edit

**Comment by raphaelmonnard** [comment]
fixed:  
![image](https://user-images.githubusercontent.com/7360153/218991812-a78c9092-5ecf-4985-a825-864b8e951597.png)
