### ISSUE TITLE
Changer footer

### ISSUE THREAD

**Issue by suzanneweber** [fablab-chaux-de-fonds/Interlab#386]
Titre : Inscrivez-vous à la newsletter 
Sous-titre : L'actualité du FabLab dans votre boite mail (environ 1x/mois) 
ou : L'actualité du FabLab dans votre boite mail une fois par mois

Comme tu préfères 🤷🏻‍♀️

**Comment by raphaelmonnard** [comment]
Restez connecté à l'actualité de votre fablab
une newsletter par mois dans votre boîte mail
