### ISSUE TITLE
Pouvoir annoncer une formation

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#40]

**Comment by suzanneweber** [comment]
# UX-Test

## Demande
Vous souhaitez ajouter une formation laser le JJ.MM.AA de 16h à 17h30

**Comment by raphaelmonnard** [comment]
Instinctivement: depuis la page d’accueil je veux passer pas formation et non "horaire et ouvertures"

**Comment by melaniethms** [comment]
Test personnel : 
Fail 😞 

- idem que raph : Instinctivement depuis la page d’accueil je veux passer par formation et non "horaire et ouvertures".
- Quand je vais sur horaire il y a déjà une plage bleu formation laser à l'heure indiquée donc je ne sais pas si je veux en rajouter une.
- Je clique sur le + puis sur formation après j'arrive sur une page depuis laquelle je ne peux pas retourner en arrière ni quitter ni même retourner sur l'accueil. (=Stress)
- Il y a déjà écrit des informations sur cette page donc je ne sais pas ce que je dois remplir 
- Je ne devine pas du tout qu'il faut cliquer sur le bouton "formation" pour y indiquer quelque chose 
- Pour simuler le choix de l'heure il faudrait que les horaires soient vides et que quand on clique dessus l'horloge qui s'affiche indique 16:00/17:30 -> puis il faut pouvoir valider et fermer l'horloge
- Récurrences : si on clique dessus il n'y a pas le choix de "pas de récurrence" 
-

**Comment by raphaelmonnard** [comment]
> idem que raph : Instinctivement depuis la page d’accueil je veux passer par formation et non "horaire et ouvertures".

La page "liste des formation" est supprimé (low fidelity wireframe). A testé si ce n'est toujours pas naturelle.

>Quand je vais sur horaire il y a déjà une plage bleu formation laser à l'heure indiquée donc je ne sais pas si je veux en rajouter une.  

Corrigé  👍

>Je clique sur le + puis sur formation après j'arrive sur une page depuis laquelle je ne peux pas retourner en arrière ni quitter ni même retourner sur l'accueil. (=Stress)

J'ai mis un lien sur le logo pour la page d’accueil. Il y la possibilité de revenir avec les flèche de l'OS. Le menu est supprimer pour plus de clarté pour le call to action.

>Il y a déjà écrit des informations sur cette page donc je ne sais pas ce que je dois remplir

Le but est de tester le flux mais pas les entrées des informations du super user comme celle-ci qui sont standard.

>Je ne devine pas du tout qu'il faut cliquer sur le bouton "formation" pour y indiquer quelque chose

Merci pour la remarque. J'ai fait une nouvelle proposition. @melaniethms Pourrais-tu tester ?

> Pour simuler le choix de l'heure il faudrait que les horaires soient vides et que quand on clique dessus l'horloge qui s'affiche indique 16:00/17:30 -> puis il faut pouvoir valider et fermer l'horloge

Le but est de tester le flux mais pas les entrées des informations du super user comme celle-ci qui sont standard.

> Récurrences : si on clique dessus il n'y a pas le choix de "pas de récurrence"

Corrigé  👍

**Comment by melaniethms** [comment]
[https://drive.google.com/file/d/1Ni5qnPslbYV_I09o-d7Gpizwy7wjXOm1/view?usp=sharing](url)
J'ai enregistré mon test et je l'ai commenté dans cette vidéo

> J'ai mis un lien sur le logo pour la page d’accueil. Il y a la possibilité de revenir avec les flèches de l'OS. Le menu est supprimé pour plus de clarté pour le call to action.
- Pour moi en termes d’UX ce n’est vraiment pas OK que le menu disparaît soudainement si on n’est pas sur un overlay.
C'est vraiment une cassure dans la cohérence du tout. L'utilisateur ne va pas soudainement se dire que la navigation change et que ça se passe avec le bouton retour en arrière de son téléphone. 

- Les boutons radios c'est ok 👍 , ça pourrait éventuellement être une petite fenêtre dropdown pour gagner de la place. 

> Le but est de tester le flux mais pas les entrées des informations du super user comme celle-ci qui sont standard.
- Si on fait tester à quelqu’un d'extérieur il ne va pas se demander si on valide juste les flux du coup s'il n’arrive pas à changer l'heure il ne va pas non plus valider la fenêtre parce qu’il ne réussit pas à remplir la mission demandée.

**Comment by raphaelmonnard** [comment]
> Pour moi en termes d’UX ce n’est vraiment pas OK que le menu disparaît soudainement si on n’est pas sur un overlay.
C'est vraiment une cassure dans la cohérence du tout. L'utilisateur ne va pas soudainement se dire que la navigation change et que ça se passe avec le bouton retour en arrière de son téléphone.

Apparemment les avis sont partagé: https://ux.stackexchange.com/questions/34884/is-it-user-friendly-to-make-the-main-navigation-bar-disappear-when-the-user-proc  
J'ai rajouter un lien pour revenir en arrière sur le calendrier. A vois si cela suffit. :-)

**Comment by raphaelmonnard** [comment]
- [ ] @raphaelmonnard réstaurer lien
