### ISSUE TITLE
Souscrire un utilisateur à un abonnement demi-tarif

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#50]
# UX-Test

## Demande:
En tant que super-user connecté sur le site, je souhaite ajouter un nouvelle abonnement à un utilisateur qui est venu lors d'une de mes ouvertures. 

## Résultat attendu:
* Le super-user se rends dans l "Espace Super User / Utilisateurs"
* Le super-user cherche un utilisateur qui doit déjà avoir un compte sur le site
* Le super-user clique sur l'utilisateur en question
* Le super-user change la catégorie d’abonnement
* Le super-user clique sur "mettre à jour"
* Le super-user comprends que l’abonnement s'est mis à jour avec le message en vert sur la page de redirection
* L’abonnement est mis à jour dans la liste des utilisateurs

Ensuite le super-user encaisse avec SumUp (rien à faire sur le site)

**Comment by melaniethms** [comment]
pareille que 51

**Comment by raphaelmonnard** [comment]
>pareille que 51

Pour la première partie du test oui, par contre après, le propriétaire peut inviter d'autre utilisateur à rejoindre l'abo.

**Comment by melaniethms** [comment]
je mettrais pas de "oups non", au pire si on s'est trompé on remet pas d'abonnement ou on met pas à jour 
Si non le test marche

**Comment by raphaelmonnard** [comment]
> je mettrais pas de "oups non", au pire si on s'est trompé on remet pas d'abonnement ou on met pas à jour Si non le test marche

FIX: [44c98c2](https://github.com/fablab-chaux-de-fonds/Interlab/pull/107/commits/44c98c292374a759db509f11396aa30dc29dc603)
