### ISSUE TITLE
Souscrire un entreprise/institution à un abonnement demi-tarif

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#51]
# UX-Test

## Demande:
On suppose ici 
* que le test #50 est réaliser pour un utilisateur (master) avec la catégorie entreprise ou institution.
* que l'utilisateur (master)  existe déjà (#21)
* qu'une équipe est crée et associée à l'utilisateur master (django-admin)

On demande ensuite à l'utilisateur (master) d'inviter d'autres utilisateur (slave) à rejoindre son abonnement.

## Résultat attendu:
* L'utilisateur (master) se connecter
* L'utilisateur (master) clique sur "Mon abonnement"
* L'utilisateur (master) clique sur "inviter un nouvelle utilisateur"
* L'utilisateur (master) rentre l'e-mail de l'utilisateur (slave)
* L'utilisateur (master) comprends que l'invitation à bien été envoyée
* L’utilisateur (slave) reçois un mail pour être informé qu'il rejoins une nouvelle équipe
* L'utilisateur (slave) est invité à créer un nouveau compte s'il existe pas encore.
* L'utilisateur comprend qu'il a un abonnement avec l'équipe sur sa page profile (/accounts/profile)

**Comment by melaniethms** [comment]
pas réussi depuis mon profil "superuserFL_test" je clique sur "voir les abonnements" (il faut rajouter un "n" à ton bouton dans le mot "abonnement") mais rien ne se passe

**Comment by raphaelmonnard** [comment]
> il faut rajouter un "n" à ton bouton dans le mot "abonnement"

Fixed: [342ea9c](https://github.com/fablab-chaux-de-fonds/Interlab/pull/107/commits/342ea9c08e8b83707aa1923a9c95249a9c46cdb4)

**Comment by melaniethms** [comment]
- nom de la personne invité : le même que le mien. 
- email pas traduit 
- lien e-mail pas le bon

**Comment by raphaelmonnard** [comment]
> lien e-mail pas le bon
FIX [f6dcfdc](https://github.com/fablab-chaux-de-fonds/Interlab/pull/107/commits/f6dcfdcf690ae9a6249f51d7dd1e471703606f7b)
