### ISSUE TITLE
Pouvoir comprendre le contenu de la formation

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#55]

**Comment by raphaelmonnard** [comment]
# UX test
## Demande
Demander à l’utilisateur le prix, la durée, les pré-requis, et les matière usinables à la laser. 

## Résultat attendu
* 40 CHF
* 1h30
* Aucun
* Bois, au tissu en passant par le plexi

**Comment by melaniethms** [comment]
Test personnel : 
Fail 😞 
Si je veux des informations sur la laser je vais forcément sur "machine" depuis la première page ce qui me redirige vers le calendrier des réservations mais pas la liste des machines donc je ne peux pas avoir d'information sur la laser.

**Comment by raphaelmonnard** [comment]
Pourrais tu re-essayer ?

**Comment by melaniethms** [comment]
[https://drive.google.com/file/d/1hx08k0uZ_MRdKb2qxzWbZXccxpUvVvUy/view?usp=sharing](url)
la vidéo du test 

C'est beaucoup mieux 👏 , juste un bug sur les boutons des prix (enfin je suppose), je ne sais pas l'expliquer je te laisse regarder la vidéo.

**Comment by raphaelmonnard** [comment]
FIX: lien prix vers abonements
NEW: ajouts des "machines associées" sur les détails de formation pour améliorer le retour en arrière.
