### ISSUE TITLE
En tant q'utilisateur débutant - je souhaite avoir des inspirations de projets - afin de pouvoir mettre en application ma formation laser/CNC/3D/plotter etc.

### ISSUE THREAD

**Issue by melaniethms** [fablab-chaux-de-fonds/Interlab#68]
### Critère d'acceptation : 
étant donné que  je suis un utilisateur débutant ou un futur utilisateur et que je suis **sur la page machines du fablab et ou formation (à définir)** , lorsque je clique sur une machine et ou une formation je veux voir **des exemples de ce que je peux réaliser** alors j'envisage de réserver ou de me former.

### UX design : 
-[ ] décider où les exemples de projets pourront apparaître 
-[ ] wireframe de la/ des page(s)
-[ ] test utilisateur pour validation

### UI design : 
-[ ] application de la charte graphique (marges, radius, grille,alignements etc...)

### Développement : 
-[ ] ?

**Comment by raphaelmonnard** [comment]
related: #74
