### ISSUE TITLE
En tant qu'utilisateur et ou non utilisateur, je souhaite également connaître les outils sans commande numérique disponibles au fablab, afin de les utiliser si j'ai un projet qui les nécessites 

### ISSUE THREAD

**Issue by melaniethms** [fablab-chaux-de-fonds/Interlab#70]
### Critère d'acceptation
étant donné que je suis un utilisateur du Fablab qui a besoin d'outils de bricolage conventionnel pour un projet, et que **je me trouve sur la page machine du site**  , lorsque  **je filtre la page** pour trouver les **outils conventionnels**  alors  **je peux les réserver** pour les utiliser sur place.

### UX : 
- [ ] définir filtrage machines
- [ ] wireframe page machine
- [ ] wireframe page réservation machines
- [ ] test utilisateur

### UI :
- [ ] maquette avec charte graphique 

### Développement : 
- [ ]

**Comment by raphaelmonnard** [comment]
related: #18 #6
