### ISSUE TITLE
En tant qu'utilisateur débutant, je souhaite savoir quand les machines sont disponibles en OpenLab, afin de bénéficier d'assitance sur la machine en cas de besoin

### ISSUE THREAD

**Issue by melaniethms** [fablab-chaux-de-fonds/Interlab#71]
### Critère d'acceptation : 
étant donné que je suis un utilisateur débutant du Fablab et que **je suis sur la page de réservation des machines** , lorsque **je clique sur le toggle "débutant"** (à définir) le système ne me montre **que** les machines pour lesquelles j'aurais une assistance (OpenLab) alors je peux **réserver les horaires qui me conviennent** 

### Epic : réservation

###UX : 
- [ ] définir overlay et ou toggle/bouton "je ne suis pas autonome"
- [ ] wireframe de la page de réservation
- [ ] test utilisateur

### UI :
- [ ] maquette intégrant la charte graphique

### développement : 
- [ ]  ?

**Comment by raphaelmonnard** [comment]
related: #56
