### ISSUE TITLE
Pouvoir réinitialiser son mot de passe

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#77]
# UX-Test
https://www.figma.com/proto/7fUjIlHUCMzteqg7mJ2PNO/interlab?page-id=154%3A0&node-id=298%3A4292&viewport=286%2C48%2C0.64&scaling=scale-down&starting-point-node-id=298%3A4292&show-proto-sidebar=1

## Demande:
Réinitialiser le mot de passe d'un utilisateur

## Résultat attendu:
l'utilisateur arrive jusqu'à la vue "mot de passe Réinitialisé"

**Comment by melaniethms** [comment]
on est dans quelle page pour la réinitialisation ? je réinitialise le mdp du user "superuserFL_test" ?

**Comment by raphaelmonnard** [comment]
Similar to #24
