### ISSUE TITLE
Pouvoir accéder à des vidéos de rappelle de formation (inkskape)

### ISSUE THREAD

**Issue by raphaelmonnard** [fablab-chaux-de-fonds/Interlab#9]

**Comment by suzanneweber** [comment]
## UX-Test

# Demande
Cela fait plus d'une année que vous avez suivi la formation laser, et aujourd'hui vous avez un nouveau projet qui nécessite l'utilisation de cette machine. Vous souhaiteriez consultez des vidéos de rappel pour vous rafraichir la mémoire.
